backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "issues"
    label: "Issues"
    label_singular: "Issue"
    description: >
      Issues are published monthly, have a collection of associated articles, and define their own custom color scheme.
    folder: "src/pages/issues"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "issue"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Blurb", name: "blurb", widget: "text"}
      - {label: "Background Color", name: "backgroundColor", widget: "string"}
      - {label: "Text Color", name: "textColor", widget: "string"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}

  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    description: >
      Articles belong to issues, they have an associated author.
    folder: "src/pages/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article"}
      - {label: "Associated Issue", name: "issue", widget: "relation", collection: "issues", searchFields: ["title"], valueField: "title"}
      - {label: "Author", name: "author", widget: "relation", collection: "authors", searchFields: ["name"], valueField: "name"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "authors"
    label: "Authors"
    label_singular: "Author"
    description: >
      Authors write articles.
    folder: "src/pages/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "author"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Bio", name: "bio", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
